### ISSUE TITLE
make site faster!

### ISSUE THREAD

**Issue by thayerve** [justinwiley/markdownbeautifier#7]
When looking at [Google Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmarkdownbeautifier.com%2F) while pairing with @paulproteus, it seems there are a few opportunities for page speed improvements.

I'm interested in looking into these issues that it raises:

* Eliminate render-blocking resources
* Remove unused JavaScript

I don't recall if we discussed this potential contribution when we talked last. Would you entertain a PR?

**Comment by justinwiley** [comment]
Hey...thanks very much to you and @paulproteus for working on this!  I would definitely entertain a PR, but realistically I will likely not deploy / update anytime the site any time soon.  I havent pushed a new version in several years...and have in fact forgotten how.  The effort of rebooting it isn't worth it to me at this point.

Do you want to take over markdownbeautifier.com? I can transfer the domain if youre interested.  Alternatively I can set you up with a AWS user account with the appropriate permissions if you want to work from there.  I'm starting a new gig so likely will not be very available to help.

**Comment by thayerve** [comment]
@justinwiley Wow, yes, I'd love to take it over! thank you so much! I'll email ya. 😃
